# docker-compose.yml
version: '3.8'

services:
  # PHP-FPM 8.4 Service
  php:
    image: php:8.4-fpm
    container_name: dev_php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./laravel-app:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - dev_network
    depends_on:
      - redis
    environment:
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d:/usr/local/etc/php/custom.d
    # Install PHP extensions needed for Laravel
    command: >
      bash -c "
      apt-get update && 
      apt-get install -y git unzip libzip-dev libpng-dev libjpeg-dev libfreetype6-dev && 
      docker-php-ext-configure gd --with-freetype --with-jpeg && 
      docker-php-ext-install pdo pdo_mysql zip gd && 
      pecl install redis && 
      docker-php-ext-enable redis && 
      php-fpm"

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: dev_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./laravel-app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dev_network
    depends_on:
      - php

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: dev_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dev_network

  # Composer (for dependency management)
  composer:
    image: composer:latest
    container_name: dev_composer
    volumes:
      - ./laravel-app:/app
    working_dir: /app
    networks:
      - dev_network
    profiles:
      - tools

networks:
  dev_network:
    driver: bridge

volumes:
  redis_data:
